version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: raw_gz_adwords
      - name: raw_gz_bing
      - name: raw_gz_criteo
      - name: raw_gz_facebook 

